{% set version = "0.9" %}
{% set name = "rw" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/rankwidth/files/rw-{{ version }}.tar.gz
  sha256: c1e03506fe25cdfcb428c051fc56b2d2affb5b06fba3f2ce756631466befb441
  patches:
    - 0001-Adapt-to-igraph-0.10.patch

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("rw", max_pin="x.x") }}

requirements:
  build:
    - libtool
    - automake
    - pkg-config
    - make
    - {{ compiler('c') }}
  host:
    - m4
    - igraph
  run:
    - {{ pin_compatible('igraph', max_pin='x.x') }}

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: https://sourceforge.net/projects/rankwidth/
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: rw calculates rank-width and rank-decompositions
  dev_url: https://sourceforge.net/p/rankwidth/code/HEAD/tree/

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
