{% set version = "0.8" %}
{% set name = "rw" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://deb.debian.org/debian/pool/main/r/rw/rw_{{ version }}+ds.orig.tar.gz
  sha256: 86dc09a765fc16d6c2a33943f099e38777513cd7a0d06d5687a9e2014ef42983

build:
  number: 1001
  skip: true  # [win]

requirements:
  build:
    - libtool
    - automake
    - pkg-config
    - make
    - {{ compiler('c') }}
  host:
    - m4
    - igraph 0.7.*

  run:
    - igraph 0.7.*

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.a
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib     # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so        # [linux]

about:
  home: https://sourceforge.net/projects/rankwidth/
  license: GPLv2
  license_file: COPYING
  summary: rw calculates rank-width and rank-decompositions
  dev_url: https://sourceforge.net/p/rankwidth/code/HEAD/tree/

extra:
  recipe-maintainers:
    - isuruf
